### ISSUE TITLE
[Druid] - increase your damage / healing

### ISSUE THREAD

**Issue by Jildor** [tobmaps/TrinityCore#1] opened 2011-04-12 09:14 UTC
Sorry I don´t know how to reproduce but i think, druids increase your damage / healing spell very, reaching sometimes inflict 72k

thx

**Comment by tobmaps** [comment] 2011-04-12 09:26
okay, it's not so easy to find what causes that problem. Would be good if you will find how to reproduce and post it.

**Comment by tobmaps** [comment] 2011-04-16 18:56
any news? I still can't reproduce it.

**Comment by Jildor** [comment] 2011-04-18 10:26
Sorry I don´t know how to reproduce.

It is very difficult to reproduce, you may be single point of failure, if I can find something.

**Comment by tobmaps** [comment] 2011-05-03 19:06
I'm closing report because there is no way to reproduce. Feel free to open it again if you find how...

**Closed as completed by tobmaps** 2011-05-03 19:06 UTC
